In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size=10,000
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9435, 4946, 7664, 7392],
 [9435, 4946, 7664, 9990],
 [9435, 9649, 7664, 2712],
 [5184, 7560, 7958, 3391, 2376],
 [5184, 7560, 7958, 3391, 9065],
 [4356, 9435, 132, 7664, 8803],
 [3059, 9445, 8144, 3391]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_length=8 # we can give to make sent of all equal length
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)  #padding before=adding zeros before
print(embedded_docs)

[[   0    0    0    0 9435 4946 7664 7392]
 [   0    0    0    0 9435 4946 7664 9990]
 [   0    0    0    0 9435 9649 7664 2712]
 [   0    0    0 5184 7560 7958 3391 2376]
 [   0    0    0 5184 7560 7958 3391 9065]
 [   0    0    0 4356 9435  132 7664 8803]
 [   0    0    0    0 3059 9445 8144 3391]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 42ms/step


array([[[-9.12485272e-03, -2.05075145e-02,  4.95761670e-02,
         -2.38180514e-02,  2.68255211e-02,  4.47872169e-02,
         -1.19459741e-02,  3.51267196e-02, -4.78673093e-02,
          4.15636785e-02],
        [-9.12485272e-03, -2.05075145e-02,  4.95761670e-02,
         -2.38180514e-02,  2.68255211e-02,  4.47872169e-02,
         -1.19459741e-02,  3.51267196e-02, -4.78673093e-02,
          4.15636785e-02],
        [-9.12485272e-03, -2.05075145e-02,  4.95761670e-02,
         -2.38180514e-02,  2.68255211e-02,  4.47872169e-02,
         -1.19459741e-02,  3.51267196e-02, -4.78673093e-02,
          4.15636785e-02],
        [-9.12485272e-03, -2.05075145e-02,  4.95761670e-02,
         -2.38180514e-02,  2.68255211e-02,  4.47872169e-02,
         -1.19459741e-02,  3.51267196e-02, -4.78673093e-02,
          4.15636785e-02],
        [ 1.36030428e-02, -4.29326408e-02,  8.28355551e-03,
          9.57466662e-04, -6.72501326e-03, -3.50978971e-02,
         -9.32574272e-03, -4.14333455e-02, -3.113682

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 9435, 4946, 7664, 7392])

In [17]:
model.predict(embedded_docs[0])  #every word with 10 dimension , 8 cross 10

1/1 [==============================] - 0s 76ms/step


array([[-0.00912485, -0.02050751,  0.04957617, -0.02381805,  0.02682552,
         0.04478722, -0.01194597,  0.03512672, -0.04786731,  0.04156368],
       [-0.00912485, -0.02050751,  0.04957617, -0.02381805,  0.02682552,
         0.04478722, -0.01194597,  0.03512672, -0.04786731,  0.04156368],
       [-0.00912485, -0.02050751,  0.04957617, -0.02381805,  0.02682552,
         0.04478722, -0.01194597,  0.03512672, -0.04786731,  0.04156368],
       [-0.00912485, -0.02050751,  0.04957617, -0.02381805,  0.02682552,
         0.04478722, -0.01194597,  0.03512672, -0.04786731,  0.04156368],
       [ 0.01360304, -0.04293264,  0.00828356,  0.00095747, -0.00672501,
        -0.0350979 , -0.00932574, -0.04143335, -0.03113682,  0.00646008],
       [-0.01918094,  0.00075411,  0.03433358, -0.03788512,  0.04418005,
         0.01804416,  0.00871322, -0.00413631,  0.01593624, -0.03311191],
       [ 0.03820369,  0.04850525, -0.02621373, -0.02250974,  0.00956202,
         0.02930542,  0.00955297,  0.02327338